spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres_user
    password: postgres_pass
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #        show_sql: true
  flyway:
    enabled: true
  docker:
    compose:
      lifecycle-management: start_only